### ISSUE TITLE
Проверка лабораторной работы №2

### ISSUE THREAD

**Issue by Anasty** [Anasty/lab2#1]
Работу выполнила:
*Кравченко Анастасия.

To: @evgeny-p

**Comment by evgeny-p** [comment]
1. Артефакты сборки не нужно коммитить в репозиторий.
1. Неконсистентное именование переменных: все в нижнем регистре, а дискриминант в верхнем.
1. Неконсистентное форматирование: унарный минус в одном случае отделен пробелом, в других — нет. Обычно унарные операторы пробелом не выделяются.

**Comment by Anasty** [comment]
Убраны артефакты сборки. Дискриминант в верхнем регистре был из соображений, что в математике он обозначается именно заглавной буквой, тогда как коэффициенты - маленькими. Исправлено.

To: @evgeny-p
